const {chromium}=require(process.env.CI_REPORT_PLAYWRIGHT||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const{pathToFileURL,fileURLToPath}=require('node:url');
const url=process.argv[2],out=process.argv[3];
if(!url||!out)throw Error('Usage: browser_v2.cjs FILE_URL OUTPUT_DIRECTORY');
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});
try{const context=await browser.newContext({offline:true,viewport:{width:1280,height:960}}),page=await context.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.goto(url);
const R=await page.locator('#report-data').evaluate(e=>JSON.parse(e.textContent));assert.equal(R.schema_version,'2.0.0');assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('#jobs button').count(),R.job_types.length);
for(const jt of R.job_types){await page.locator(`[data-type="${jt.id}"]`).click();for(const size of ['32','64']){await page.locator('#size').selectOption(size);let w=R.windows.find(w=>w.type_id===jt.id&&w.size===Number(size)&&w.page===0);await verifyWindow(w);if(size==='32'&&w.has_older){await page.locator('#older').click();w=R.windows.find(v=>v.id===w.older_window_id);await verifyWindow(w);await page.locator('#latest').click();}}
}
async function verifyWindow(w){assert.equal(await page.locator('#history tr').count(),w.attempt_ids.length);assert.equal(await page.locator('#chart [data-attempt]').count(),w.attempt_ids.length);for(const metric of ['queue','execution','total'])assert.equal(await page.locator(`[data-metric="${metric}"]`).getAttribute('data-seconds'),String(w.findings.metrics[metric].median_seconds));
for(const id of w.attempt_ids){await page.locator(`#history tr[data-attempt="${id}"] button`).click();assert.match(await page.locator('#detail-title').innerText(),new RegExp('#'+id+' '));const a=R.attempts.find(a=>a.id===id);assert.equal(await page.locator('#evidence tr').count(),a.trace?.evidence.length||0);for(const k of ['queue','execution','total'])assert.equal(await page.locator(`#history tr[data-attempt="${id}"] [data-timing="${k}"]`).getAttribute('data-seconds'),String(a.timing[k].value_seconds));}
for(const code of w.findings.priority_codes){const c=w.findings.categories.find(c=>c.code===code);assert.equal(Number(await page.locator(`[data-category="${code}"]`).getAttribute('data-seconds')),c.median_seconds);if(c.representative){await page.locator(`[data-category="${code}"] button`).click();assert.match(await page.locator('#detail-title').innerText(),new RegExp('#'+c.representative.attempt_id+' '));if(c.representative.evidence_id)assert.equal(await page.locator('#evidence tr[aria-selected="true"]').getAttribute('data-evidence'),c.representative.evidence_id);}}
}
await page.setViewportSize({width:320,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.emulateMedia({colorScheme:'dark'});await page.goto(url);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'report-v2-mobile.png'),fullPage:false});await page.setViewportSize({width:1280,height:960});await page.emulateMedia({colorScheme:'light'});await page.goto(url);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'report-v2.png'),fullPage:false});
const standalone=path.join(out,'standalone.html');fs.copyFileSync(fileURLToPath(url),standalone);await page.goto(pathToFileURL(standalone).href);assert.equal(await page.locator('#jobs button').count(),R.job_types.length);fs.unlinkSync(standalone);assert.deepEqual(errors,[]);assert.equal(requests.some(u=>!u.startsWith('file:')),false);
const result={offline:true,job_types:R.job_types.length,windows:R.windows.length,attempts:R.source.retained_job_ids.length,checks:['all job/window/attempt selections','JSON numeric parity','evidence references','representative costs','320px overflow','light/dark','moved standalone file','no external network or JS errors']};fs.writeFileSync(path.join(out,'browser-v2-results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
