const {chromium}=require(process.env.CI_REPORT_PLAYWRIGHT || 'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {fileURLToPath,pathToFileURL}=require('node:url');
const url=process.argv[2],output=process.argv[3];
if(!url||!output)throw Error('Usage: browser_release_check.cjs FILE_URL OUTPUT_DIRECTORY');
(async()=>{
  fs.mkdirSync(output,{recursive:true});
  const browser=await chromium.launch({channel:'chrome',headless:true});
  try{
    const context=await browser.newContext({viewport:{width:1280,height:1000},offline:true});
    const page=await context.newPage(),errors=[],requests=[];
    page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
    const data=JSON.parse(fs.readFileSync(path.join(path.dirname(fileURLToPath(url)),'report.json'),'utf8'));
    const g=data.release_history.groups.find(g=>g.name==='build');
    await page.goto(url);
    assert.equal(await page.locator('#release-panel').getAttribute('open'),null);
    assert.match(await page.locator('#situation').innerText(),/not enough|No successful/i);
    await page.locator('#release-panel summary').click();
    assert.equal(await page.locator('.release-attempt').count(),32);
    assert.match(await page.locator('#release-comparison').innerText(),/Exploratory/);
    assert.match(await page.locator('#release-comparison').innerText(),new RegExp(String(g.execution_change.delta_seconds)));
    assert.match(await page.locator('#release-context').innerText(),/configuration.*not verified/i);
    const run=page.locator('.release-attempt[data-id="2700"] [data-component="execution"]');
    assert.equal(Number(await run.getAttribute('data-seconds')),200);
    await page.locator('#release-window').selectOption('64');
    assert.equal(await page.locator('.release-attempt').count(),64);
    const missing=page.locator('.release-attempt[data-id="2090"]');
    assert.equal(await missing.locator('[data-component="execution"]').count(),0);
    await missing.focus();await page.keyboard.press('Enter');
    assert.match(await page.locator('#release-selected').innerText(),/v1.8/);
    assert.match(await page.locator('#release-selected').innerText(),/not available/);
    await page.locator('.release-attempt[data-id="2122"]').click();
    assert.match(await page.locator('#release-selected').innerText(),/failed/);
    assert.match(await page.locator('#release-selected').innerText(),/Excluded/);
    await page.locator('#release-job').selectOption('1');
    assert.match(await page.locator('#release-purpose').innerText(),/publish/);
    assert.equal(await page.locator('.release-attempt[data-id="2700"]').count(),0);
    await page.locator('#release-job').selectOption('0');
    await page.screenshot({path:path.join(output,'release-report.png'),fullPage:true});
    await page.setViewportSize({width:360,height:800});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    assert.equal(await page.locator('#release-chart').evaluate(e=>e.scrollWidth<=e.clientWidth),true);
    await page.emulateMedia({colorScheme:'dark'});
    await page.screenshot({path:path.join(output,'release-mobile.png'),fullPage:true});
    const detached=path.join(output,'standalone.html');fs.copyFileSync(fileURLToPath(url),detached);
    await page.goto(pathToFileURL(detached).href);await page.locator('#release-panel summary').click();
    assert.equal(await page.locator('.release-attempt').count(),32);fs.unlinkSync(detached);
    assert.deepEqual(errors,[]);assert.equal(requests.some(u=>!u.startsWith('file:')),false);
    const result={offline:true,checks:['same-ref default','32/64 release attempts','explicit refs and sample sizes','execution/queue JSON parity','unknown versus zero','failed attempts excluded from baseline','keyboard selection','job selection','mobile overflow','dark mode','standalone HTML','no network or JS errors']};
    fs.writeFileSync(path.join(output,'release-browser-results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
